# Generated by Django 6.0.5 on 2026-05-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
